# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Inte sÃ¥ lagom
#email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Talk is cheap.
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://tomszilagyi.github.io" # the base hostname & protocol for your site
github_username:  tomszilagyi

# Build settings
markdown: kramdown

permalink: "/:year/:month/:title"

include: ['_pages']

host: 0.0.0.0
